"""migrate

Revision ID: c8ddeb531e7b
Revises: 221b142f9571
Create Date: 2018-04-20 14:11:36.741457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ddeb531e7b'
down_revision = '221b142f9571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
